language: go
install: true
go:
  - 1.8.x
  - 1.7.x
  - 1.6.x
  - master
env:
  global:
    - GOARCH=amd64
    - COVERALLS_TOKEN=wyZjjcuWXLplM6dMfMfNLCphJBWgTtGNK
before_install:
  - go get ./...
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls
script:
  - make test-travis
matrix:
  allow_failures:
    - go: master
